# Generated by Django 4.2.13 on 2024-07-07 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="username",
            field=models.CharField(default="prosper", max_length=25, unique=True),
            preserve_default=False,
        ),
    ]
