# Generated by Django 5.0.6 on 2024-05-25 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_rent_invoice_account_shop_charges_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('shop', models.CharField(max_length=4)),
                ('customer', models.CharField(max_length=5)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('account', models.CharField(choices=[('Nina Sky', 'Nina'), ('Chairman', 'Chairman')], default='Nina Sky', max_length=20)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
            ],
        ),
    ]
