# Generated by Django 5.0.6 on 2024-05-25 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='outstanding',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='receipt',
            name='rent_invoice_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
