# Generated by Django 4.2.13 on 2024-07-07 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_profile_shop"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="shop",
        ),
    ]
