# Generated by Django 4.2.13 on 2025-05-21 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_profile_dob_profile_nature_profile_occupation_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
