# Generated by Django 4.2.13 on 2025-05-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0007_customuser_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="role",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_approved",
            field=models.BooleanField(default=True),
        ),
    ]
