# Generated by Django 4.2.13 on 2025-05-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0008_remove_customuser_role_alter_customuser_is_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(
                default="09036356792",
                help_text="Enter your phone number",
                max_length=11,
            ),
            preserve_default=False,
        ),
    ]
