# Generated by Django 5.0.6 on 2024-05-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='approval',
            field=models.BooleanField(default=False),
        ),
    ]
