# Generated by Django 5.0.6 on 2024-05-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customer_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('renewal', 'renewal'), ('exited', 'exited')], default='', max_length=10),
        ),
    ]
