# Generated by Django 5.0.6 on 2024-05-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_customer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='no',
            field=models.CharField(max_length=5),
        ),
    ]
