# Generated by Django 5.0.6 on 2024-06-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_customer_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='exitdate',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
