# Generated by Django 5.0.6 on 2024-06-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_customer_exitdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='nextdue',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
