# Generated by Django 4.2.13 on 2024-08-05 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0006_customer_data_entry_officer_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="approval_officer_note",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="review_officer_note",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
