# Generated by Django 4.2.13 on 2024-11-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0011_customer_outstanding_balance_alter_customer_nature"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={"ordering": ["no"]},
        ),
        migrations.AlterField(
            model_name="customer",
            name="nature",
            field=models.CharField(
                choices=[
                    ("Supermarket", "Supermarket"),
                    ("Laundry", "Laundry"),
                    ("Pharmacy", "Pharmacy"),
                    ("Courier/Dispatch", "Courier/Dispatch"),
                    ("Banking/Insurance", "Banking/Insurance"),
                    ("Barbing/Salon", "Barbing/Salon"),
                    ("Restaurant", "Restaurant"),
                    ("Food and Drinks", "Food and Drinks"),
                    ("Makeup Artist", "Makeup Artist"),
                    ("Building", "Building"),
                    ("Tailoring", "Tailoring"),
                    ("Studio", "Studio"),
                    ("Beauty Salon", "Beauty Salon"),
                    ("Bakery", "Bakery"),
                    ("Wine Seller", "Wine Seller"),
                    ("Logistics", "Logistics"),
                    ("Clothing", "Clothing"),
                    ("Fabrics", "Fabrics"),
                    ("Oriflame Dealer", "Oriflame Dealer"),
                    ("Fruit Seller", "Fruit Seller"),
                    ("Communication", "Communication"),
                    ("Business Centre", "Business Centre"),
                    ("Bank", "Bank"),
                    ("Tv Repair", "Tv Repair"),
                    ("Hair Business", "Hair Business"),
                    ("Consultancy", "Consultancy"),
                    ("Skin Beauty Store", "Skin Beauty Store"),
                    ("Dispatch Office", "Dispatch Office"),
                    ("Loan Business", "Loan Business"),
                    ("Children Wears", "Children Wears"),
                    ("Electrical/Electronics Store", "Electrical/Electronics Store"),
                    ("Home Wears Store", "Home Wears Store"),
                    ("Travel Agency", "Travel Agency"),
                    ("Photo Studio", "Photo Studio"),
                    ("Law Firm", "Law Firm"),
                    ("Graphic Design and Branding", "Graphic Design and Branding"),
                    ("Perfumery", "Perfumery"),
                    ("NGO", "NGO"),
                    ("Others", "Others"),
                ],
                default="",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="no",
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="status",
            field=models.CharField(
                choices=[("new", "New"), ("renewal", "Renewal"), ("exited", "Exited")],
                default="",
                max_length=10,
            ),
        ),
    ]
