# Generated by Django 4.2.13 on 2024-11-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_alter_customer_options_alter_customer_nature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='outstanding_balance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
