# Generated by Django 4.2.13 on 2024-11-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_alter_customer_outstanding_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='other_state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
