# Generated by Django 4.2.13 on 2025-05-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0016_alter_customer_nature_alter_customer_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="is_reviewed",
            field=models.BooleanField(default=True),
        ),
    ]
