# Generated by Django 4.2.13 on 2025-05-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0017_alter_customer_is_reviewed"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default="2025-05-11"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customer",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
