# Generated by Django 4.2.13 on 2025-05-31 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_customer_created_at_customer_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
