# Generated by Django 5.0.6 on 2024-05-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='floor',
            field=models.CharField(choices=[('G', 'Ground Floor'), ('1', 'First Floor'), ('2', 'Second Floor')], default='', max_length=20, null=True),
        ),
    ]
