# Generated by Django 5.0.6 on 2024-05-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_rate_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='floor',
            field=models.CharField(choices=[('G', 'Ground Floor'), ('1', 'First Floor'), ('2', 'Second Floor')], max_length=20),
        ),
    ]
