# Generated by Django 4.2.13 on 2024-07-13 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0006_rent_is_paid_rent_managed_by_alter_rent_date_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='customer',
            field=models.ForeignKey(limit_choices_to={'is_staff': False}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
