# Generated by Django 4.2.13 on 2024-07-29 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0010_rent_is_expired"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rent",
            name="managed_by",
        ),
    ]
