# Generated by Django 4.2.13 on 2024-07-29 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_remove_shop_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='no',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
