# Generated by Django 4.2.13 on 2024-07-30 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_shop_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='approval',
            field=models.BooleanField(default=(('In review', 'In review'), ('Pending Approval', 'Pending Approval'))),
        ),
    ]
