# Generated by Django 4.2.13 on 2024-08-06 10:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0014_rent_rent_start_alter_rent_date_paid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop",
            name="no",
            field=models.CharField(
                max_length=5,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(5)],
            ),
        ),
    ]
