# Generated by Django 4.2.13 on 2024-07-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_shop_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='approval',
            field=models.CharField(choices=[('In review', 'In review'), ('Pending Approval', 'Pending Approval')], max_length=100),
        ),
    ]
