# Generated by Django 4.2.13 on 2024-07-30 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_shop_approval'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='approval',
            new_name='shop_approval',
        ),
    ]
