# Generated by Django 4.2.13 on 2024-08-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0016_alter_shop_no"),
    ]

    operations = [
        migrations.CreateModel(
            name="Income",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("daily", models.DecimalField(decimal_places=2, max_digits=15)),
                ("weekly", models.DecimalField(decimal_places=2, max_digits=15)),
                ("yearly", models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.AlterField(
            model_name="shop",
            name="type",
            field=models.CharField(
                choices=[
                    ("Platinum", "Platinum"),
                    ("Titanium", "Titanium"),
                    ("Diamond", "Diamond"),
                    ("Premium", "Premium"),
                    ("Gold", "Gold"),
                    ("Silver", "Silver"),
                ],
                max_length=10,
            ),
        ),
    ]
