# Generated by Django 4.2.13 on 2024-08-08 04:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_income_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 8, 4, 21, 10, 600456, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='income',
            name='name',
            field=models.CharField(choices=[('Nina', 'Nina'), ('Chairman', 'Chariman')], max_length=200),
        ),
    ]
