# Generated by Django 4.2.13 on 2024-08-09 17:26

import datetime
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0020_alter_income_date_created_alter_income_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="income",
            name="daily",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=15
            ),
        ),
        migrations.AlterField(
            model_name="income",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 8, 9, 17, 26, 18, 814901, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="income",
            name="weekly",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=15
            ),
        ),
        migrations.AlterField(
            model_name="income",
            name="yearly",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=15
            ),
        ),
    ]
