# Generated by Django 4.2.13 on 2024-08-10 08:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0022_alter_income_date_created_paymentslip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="income",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 8, 10, 8, 35, 6, 793945, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="paymentslip",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
