# Generated by Django 4.2.13 on 2024-11-06 07:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_shop_new_shop_price_alter_income_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='caution_fee',
            field=models.DecimalField(decimal_places=2, default=100000.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='income',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 6, 7, 41, 17, 154847, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='rent',
            name='rent_type',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Yearly', 'Yearly'), ('Lease', 'Lease'), ('1 year', '1 year'), ('2 year(s)', '2 years(s)'), ('5 years', '5 years')], max_length=20),
        ),
    ]
