# Generated by Django 4.2.13 on 2025-05-21 09:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0032_paymentslip_is_reviewed_alter_income_date_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="income",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 5, 21, 9, 8, 37, 99421, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
