# Generated by Django 4.2.13 on 2025-05-21 09:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0033_alter_income_date_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="income",
            name="date_created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
