# Generated by Django 4.2.13 on 2025-05-22 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_rent_assigned_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shop'),
        ),
    ]
